// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ChurchApp.Application.Infrastructure.CompiledModels
{
    public partial class ChurchAppDbContextModel
    {
        private ChurchAppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("f5f7bee9-dcb0-4f9e-a507-b3486c34424a"), entityTypeCount: 9)
        {
        }

        partial void Initialize()
        {
            var donation = DonationEntityType.Create(this);
            var donationAccount = DonationAccountEntityType.Create(this);
            var donationAudit = DonationAuditEntityType.Create(this);
            var family = FamilyEntityType.Create(this);
            var familyMember = FamilyMemberEntityType.Create(this);
            var member = MemberEntityType.Create(this);
            var financialObligation = FinancialObligationEntityType.Create(this);
            var report = ReportEntityType.Create(this);
            var summary = SummaryEntityType.Create(this);

            DonationEntityType.CreateForeignKey1(donation, donationAccount);
            DonationEntityType.CreateForeignKey2(donation, member);
            DonationEntityType.CreateForeignKey3(donation, financialObligation);
            DonationAccountEntityType.CreateForeignKey1(donationAccount, member);
            DonationAuditEntityType.CreateForeignKey1(donationAudit, donation);
            FamilyMemberEntityType.CreateForeignKey1(familyMember, family);
            FamilyMemberEntityType.CreateForeignKey2(familyMember, member);
            FinancialObligationEntityType.CreateForeignKey1(financialObligation, member);
            ReportEntityType.CreateForeignKey1(report, family);
            ReportEntityType.CreateForeignKey2(report, member);
            SummaryEntityType.CreateForeignKey1(summary, family);
            SummaryEntityType.CreateForeignKey2(summary, member);

            DonationEntityType.CreateAnnotations(donation);
            DonationAccountEntityType.CreateAnnotations(donationAccount);
            DonationAuditEntityType.CreateAnnotations(donationAudit);
            FamilyEntityType.CreateAnnotations(family);
            FamilyMemberEntityType.CreateAnnotations(familyMember);
            MemberEntityType.CreateAnnotations(member);
            FinancialObligationEntityType.CreateAnnotations(financialObligation);
            ReportEntityType.CreateAnnotations(report);
            SummaryEntityType.CreateAnnotations(summary);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
