// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ChurchApp.Application.Infrastructure.CompiledModels
{
    public partial class ChurchAppDbContextModel
    {
        private ChurchAppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("5aa2f139-133f-4634-8a5d-6d80e9d7aed9"), entityTypeCount: 12)
        {
        }

        partial void Initialize()
        {
            var donation = DonationEntityType.Create(this);
            var donationAccount = DonationAccountEntityType.Create(this);
            var donationAudit = DonationAuditEntityType.Create(this);
            var family = FamilyEntityType.Create(this);
            var familyMember = FamilyMemberEntityType.Create(this);
            var member = MemberEntityType.Create(this);
            var financialObligation = FinancialObligationEntityType.Create(this);
            var report = ReportEntityType.Create(this);
            var summary = SummaryEntityType.Create(this);
            var rawTransaction = RawTransactionEntityType.Create(this);
            var dues = DuesEntityType.Create(this, financialObligation);
            var pledge = PledgeEntityType.Create(this, financialObligation);

            DonationEntityType.CreateForeignKey1(donation, donationAccount);
            DonationEntityType.CreateForeignKey2(donation, member);
            DonationEntityType.CreateForeignKey3(donation, financialObligation);
            DonationAccountEntityType.CreateForeignKey1(donationAccount, member);
            DonationAuditEntityType.CreateForeignKey1(donationAudit, donation);
            FamilyMemberEntityType.CreateForeignKey1(familyMember, family);
            FamilyMemberEntityType.CreateForeignKey2(familyMember, member);
            FinancialObligationEntityType.CreateForeignKey1(financialObligation, member);
            ReportEntityType.CreateForeignKey1(report, family);
            ReportEntityType.CreateForeignKey2(report, member);
            SummaryEntityType.CreateForeignKey1(summary, family);
            SummaryEntityType.CreateForeignKey2(summary, member);
            RawTransactionEntityType.CreateForeignKey1(rawTransaction, donation);

            DonationEntityType.CreateAnnotations(donation);
            DonationAccountEntityType.CreateAnnotations(donationAccount);
            DonationAuditEntityType.CreateAnnotations(donationAudit);
            FamilyEntityType.CreateAnnotations(family);
            FamilyMemberEntityType.CreateAnnotations(familyMember);
            MemberEntityType.CreateAnnotations(member);
            FinancialObligationEntityType.CreateAnnotations(financialObligation);
            ReportEntityType.CreateAnnotations(report);
            SummaryEntityType.CreateAnnotations(summary);
            RawTransactionEntityType.CreateAnnotations(rawTransaction);
            DuesEntityType.CreateAnnotations(dues);
            PledgeEntityType.CreateAnnotations(pledge);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
