// <auto-generated />
using ChurchApp.Application.Infrastructure;
using ChurchApp.Application.Infrastructure.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ChurchAppDbContext), typeof(ChurchAppDbContextModel))]
