// <auto-generated />
using System;
using System.Reflection;
using ChurchApp.Application.Domain.Donations;
using ChurchApp.Application.Domain.Transactions;
using ChurchApp.Application.Infrastructure.ValueConverters;
using ChurchApp.Primitives.Donations;
using ChurchApp.Primitives.Transactions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ChurchApp.Application.Infrastructure.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class RawTransactionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "ChurchApp.Application.Domain.Transactions.RawTransaction",
                typeof(RawTransaction),
                baseEntityType,
                propertyCount: 13,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 4,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(RawTransaction).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var amount = runtimeEntityType.AddProperty(
                "Amount",
                typeof(DonationAmount),
                propertyInfo: typeof(RawTransaction).GetProperty("Amount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<Amount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                precision: 18,
                scale: 2,
                valueConverter: new DonationAmountValueConverter(),
                valueComparer: new DonationAmountValueComparer());
            amount.SetSentinelFromProviderValue(0m);
            amount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var createdAtUtc = runtimeEntityType.AddProperty(
                "CreatedAtUtc",
                typeof(DateTime),
                propertyInfo: typeof(RawTransaction).GetProperty("CreatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<CreatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var gmailMessageId = runtimeEntityType.AddProperty(
                "GmailMessageId",
                typeof(string),
                propertyInfo: typeof(RawTransaction).GetProperty("GmailMessageId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<GmailMessageId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            gmailMessageId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var memo = runtimeEntityType.AddProperty(
                "Memo",
                typeof(string),
                propertyInfo: typeof(RawTransaction).GetProperty("Memo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<Memo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            memo.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var provider = runtimeEntityType.AddProperty(
                "Provider",
                typeof(TransactionProvider),
                propertyInfo: typeof(RawTransaction).GetProperty("Provider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<Provider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(int));
            provider.SetSentinelFromProviderValue(0);
            provider.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var providerTransactionId = runtimeEntityType.AddProperty(
                "ProviderTransactionId",
                typeof(string),
                propertyInfo: typeof(RawTransaction).GetProperty("ProviderTransactionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<ProviderTransactionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            providerTransactionId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var rawContentJson = runtimeEntityType.AddProperty(
                "RawContentJson",
                typeof(string),
                propertyInfo: typeof(RawTransaction).GetProperty("RawContentJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<RawContentJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            rawContentJson.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            rawContentJson.AddAnnotation("Relational:ColumnType", "text");

            var resolvedDonationId = runtimeEntityType.AddProperty(
                "ResolvedDonationId",
                typeof(Guid?),
                propertyInfo: typeof(RawTransaction).GetProperty("ResolvedDonationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<ResolvedDonationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            resolvedDonationId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var senderHandle = runtimeEntityType.AddProperty(
                "SenderHandle",
                typeof(string),
                propertyInfo: typeof(RawTransaction).GetProperty("SenderHandle", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<SenderHandle>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            senderHandle.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var senderName = runtimeEntityType.AddProperty(
                "SenderName",
                typeof(string),
                propertyInfo: typeof(RawTransaction).GetProperty("SenderName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<SenderName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            senderName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(RawTransactionStatus),
                propertyInfo: typeof(RawTransaction).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(int));
            status.SetSentinelFromProviderValue(0);
            status.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var transactionDate = runtimeEntityType.AddProperty(
                "TransactionDate",
                typeof(DateOnly),
                propertyInfo: typeof(RawTransaction).GetProperty("TransactionDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<TransactionDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));
            transactionDate.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { providerTransactionId },
                unique: true);
            index.AddAnnotation("Relational:Name", "IX_RawTransactions_ProviderTransactionId_Unique");

            var index0 = runtimeEntityType.AddIndex(
                new[] { resolvedDonationId });

            var index1 = runtimeEntityType.AddIndex(
                new[] { status });
            index1.AddAnnotation("Relational:Name", "IX_RawTransactions_Status");

            var index2 = runtimeEntityType.AddIndex(
                new[] { provider, status });
            index2.AddAnnotation("Relational:Name", "IX_RawTransactions_Provider_Status");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ResolvedDonationId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.SetNull);

            var resolvedDonation = declaringEntityType.AddNavigation("ResolvedDonation",
                runtimeForeignKey,
                onDependent: true,
                typeof(Donation),
                propertyInfo: typeof(RawTransaction).GetProperty("ResolvedDonation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RawTransaction).GetField("<ResolvedDonation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "RawTransactions");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
