// <auto-generated />
using System;
using ChurchApp.Application.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChurchApp.Application.Migrations
{
    [DbContext(typeof(ChurchAppDbContext))]
    [Migration("20260301023114_AddSummaryModel")]
    partial class AddSummaryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ChurchApp.Application.Domain.Donations.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DonationAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DonationAccountId");

                    b.HasIndex("MemberId");

                    b.HasIndex("DonationDate", "Type");

                    b.ToTable("Donations", t =>
                        {
                            t.HasCheckConstraint("CK_Donations_Amount_NotZero", "\"Amount\" <> 0");
                        });
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Donations.DonationAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("Method", "Handle")
                        .IsUnique();

                    b.ToTable("DonationAccounts");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Families.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Families.FamilyMember", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("FamilyId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MemberId");

                    b.HasIndex("Type", "GeneratedAtUtc");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Reports.Summary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DonationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("Type", "PeriodType", "StartDate", "EndDate", "GeneratedAtUtc");

                    b.ToTable("Summaries", t =>
                        {
                            t.HasCheckConstraint("CK_Summaries_TotalAmount_NotNegative", "\"TotalAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Donations.Donation", b =>
                {
                    b.HasOne("ChurchApp.Application.Domain.Donations.DonationAccount", "DonationAccount")
                        .WithMany("Donations")
                        .HasForeignKey("DonationAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChurchApp.Application.Domain.Members.Member", "Member")
                        .WithMany("Donations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonationAccount");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Donations.DonationAccount", b =>
                {
                    b.HasOne("ChurchApp.Application.Domain.Members.Member", "Member")
                        .WithMany("DonationAccounts")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Families.FamilyMember", b =>
                {
                    b.HasOne("ChurchApp.Application.Domain.Families.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChurchApp.Application.Domain.Members.Member", "Member")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Reports.Report", b =>
                {
                    b.HasOne("ChurchApp.Application.Domain.Families.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChurchApp.Application.Domain.Members.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Family");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Reports.Summary", b =>
                {
                    b.HasOne("ChurchApp.Application.Domain.Members.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Donations.DonationAccount", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Families.Family", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ChurchApp.Application.Domain.Members.Member", b =>
                {
                    b.Navigation("DonationAccounts");

                    b.Navigation("Donations");

                    b.Navigation("FamilyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
